#!/bin/sh

### Exports ###
export PF_INFO="os pkgs memory wm shell editor palette"
export LC_ALL="en_US.UTF-8"
export TZ="Africa/Cairo"
export HARDWARECLOCK=localtime
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="brave"
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export ZDOTDIR=$HOME/.config/zsh
if [ -d "$HOME/.local/share/bin" ] ;
  then PATH="$HOME/.local/share/bin:$PATH"
fi
if [ -d "$HOME/.local/bin" ] ;
  then PATH="$HOME/.local/bin:$PATH"
fi
