#!/bin/sh

### Aliases ###
alias v="nvim"
alias cp="cp -ri"
alias rm="rm -ri"
alias ls='exa --group-directories-first --icons -la'
alias ll='exa'
alias up='sudo pacman -Syyu'
alias orphans='sudo pacman -Qtdq | sudo pacman -Rns -'
